[Settings]
; 由小胖维护的覆盖配置；仅覆盖必要项，其余走上游默认
source_file = config/user_demo.txt
final_file = output/user_result.txt
; 台标库（频道名.png）
logo_url = https://www.xn--rgv465a.top/tvlogo
logo_type = png
; CDN 加速（仅作用于 raw.githubusercontent.com 类地址）
cdn_url = https://gh-proxy.com/
